apiVersion: v1
kind: ServiceAccount
metadata:
  name: packet-capture-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packet-capture-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packet-capture-binding
subjects:
  - kind: ServiceAccount
    name: packet-capture-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: packet-capture-role
  apiGroup: rbac.authorization.k8s.io
